#!/usr/bin/env python

import argparse
import subprocess
import sys
from functools import cache
from pathlib import Path


@cache
def get_path() -> Path:
    base_path = Path('/sys/class/backlight')
    if not base_path.is_dir():
        raise OSError('Cannot find backlight sys directory')

    for path in base_path.iterdir():
        if not path.is_dir():
            continue
        if not (path / 'brightness').exists():
            continue
        if not (path / 'max_brightness').exists():
            continue
        return path

    raise OSError('Cannot find any backlight interface')


@cache
def get_name() -> str:
    return get_path().name


def get_current() -> int:
    return int((get_path() / 'brightness').read_text())


@cache
def get_max() -> int:
    return int((get_path() / 'max_brightness').read_text())


@cache
def get_rate() -> float:
    return get_max() / 100


def action_get(args):
    print(round(get_current() / get_rate()))


def action_update(args):
    value = args.value * get_rate()
    if args.transform:
        value = args.transform(value)
    value = min(max(round(value), 0), get_max())
    subprocess.run(['./set-backlight', get_name(), str(value)])
    action_get(args)


def action_off(args):
    subprocess.run(['xset', 'dpms', 'force', 'off'])


def get_parser():
    parser = argparse.ArgumentParser()
    parser.set_defaults(action=action_get)
    subparsers = parser.add_subparsers()

    get_parser = subparsers.add_parser('get')

    set_parser = subparsers.add_parser('set')
    set_parser.add_argument('value', type=int)
    set_parser.set_defaults(action=action_update, transform=None)

    inc_parser = subparsers.add_parser('inc')
    inc_parser.add_argument('value', type=int)
    inc_parser.set_defaults(action=action_update, transform=lambda v: get_current() + v)

    dec_parser = subparsers.add_parser('dec')
    dec_parser.add_argument('value', type=int)
    dec_parser.set_defaults(action=action_update, transform=lambda v: get_current() - v)

    off_parser = subparsers.add_parser('off')
    off_parser.set_defaults(action=action_off)

    return parser


def main():
    parser = get_parser()
    args = parser.parse_args()
    try:
        args.action(args)
    except Exception as e:
        print(e, file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
